# ~/.GH/Qompass/.github/workflows/update-qompass.yml
# --------------------------------------------------
# Copyright (C) 2025 Qompass AI, All rights reserved

# .github/workflows/update-qompass.yml
name: Update Repo List in README

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-repo-list:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install requests

      - name: Update repo list in README.md
        run: |
          python .github/scripts/update_repo_list.py

      - name: Commit and push changes
        run: |
          git config --global user.name "phaedrusflow"
          git config --global user.email "map@qompass.ai"
          git add README.md
          git commit -m "chore: update repo list [skip ci]" || echo "No changes to commit"
          git push
